publish

diff --git a/.github/workflows/publish-package.yml b/.github/workflows/publish-package.yml
--- a/.github/workflows/publish-package.yml
+++ b/.github/workflows/publish-package.yml
@@ -79,114 +79,114 @@ jobs:
           name: nuget-package
           path: ${{ env.ARTIFACT_PATH }}
 
-  sonar_scan:
-    runs-on: windows-latest
-    needs: build  
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2 
+  # sonar_scan:
+  #   runs-on: windows-latest
+  #   needs: build  
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v2 
 
-      - name: Set up JDK 17
-        uses: actions/setup-java@v4
-        with:
-          java-version: 17
-          distribution: 'zulu'
+  #     - name: Set up JDK 17
+  #       uses: actions/setup-java@v4
+  #       with:
+  #         java-version: 17
+  #         distribution: 'zulu'
 
-      - name: Cache SonarQube Cloud packages
-        uses: actions/cache@v4
-        with:
-          path: ~\sonar\cache
-          key: ${{ runner.os }}-sonar
-          restore-keys: ${{ runner.os }}-sonar
+  #     - name: Cache SonarQube Cloud packages
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: ~\sonar\cache
+  #         key: ${{ runner.os }}-sonar
+  #         restore-keys: ${{ runner.os }}-sonar
 
-      - name: Cache SonarQube Cloud scanner
-        id: cache-sonar-scanner
-        uses: actions/cache@v4
-        with:
-          path: .\.sonar\scanner
-          key: ${{ runner.os }}-sonar-scanner
-          restore-keys: ${{ runner.os }}-sonar-scanner
+  #     - name: Cache SonarQube Cloud scanner
+  #       id: cache-sonar-scanner
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: .\.sonar\scanner
+  #         key: ${{ runner.os }}-sonar-scanner
+  #         restore-keys: ${{ runner.os }}-sonar-scanner
 
-      - name: Install SonarQube Cloud scanner
-        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
-        shell: powershell
-        run: |
-          New-Item -Path .\.sonar\scanner -ItemType Directory
-          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
+  #     - name: Install SonarQube Cloud scanner
+  #       if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
+  #       shell: powershell
+  #       run: |
+  #         New-Item -Path .\.sonar\scanner -ItemType Directory
+  #         dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
 
-      - name: Build and analyze
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   
-        shell: powershell
-        run: |
-          .\.sonar\scanner\dotnet-sonarscanner begin /k:"${{ vars.PROJECT_KEY }}" /o:"${{ vars.PROJECT_NAME }}" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
-          dotnet build
-          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
+  #     - name: Build and analyze
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
+  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   
+  #       shell: powershell
+  #       run: |
+  #         .\.sonar\scanner\dotnet-sonarscanner begin /k:"${{ vars.PROJECT_KEY }}" /o:"${{ vars.PROJECT_NAME }}" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
+  #         dotnet build
+  #         .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
 
-      - name: Check Quality Gate
-        run: |
-            sleep 5  
-            QUALITY_GATE_STATUS=$(curl -s -H "Authorization: Bearer ${{ secrets.SONAR_TOKEN }}" "https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ inputs.project_key }}")           
-            echo "Quality Gate Status Response: $QUALITY_GATE_STATUS"           
-            PROJECT_STATUS=$(echo "$QUALITY_GATE_STATUS" | jq -r '.projectStatus.status')            
-            ALL_CONDITIONS_OK=$(echo "$QUALITY_GATE_STATUS" | jq -r '.projectStatus.conditions | all(.status == "OK")')
-            if [[ "$PROJECT_STATUS" != "OK" || "$ALL_CONDITIONS_OK" != "true" ]]; then
-              echo "Quality Gate failed. Stopping the workflow."
-              exit 1
-            else
-              echo "Quality Gate passed."
-            fi
-        shell: bash
+  #     - name: Check Quality Gate
+  #       run: |
+  #           sleep 5  
+  #           QUALITY_GATE_STATUS=$(curl -s -H "Authorization: Bearer ${{ secrets.SONAR_TOKEN }}" "https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ inputs.project_key }}")           
+  #           echo "Quality Gate Status Response: $QUALITY_GATE_STATUS"           
+  #           PROJECT_STATUS=$(echo "$QUALITY_GATE_STATUS" | jq -r '.projectStatus.status')            
+  #           ALL_CONDITIONS_OK=$(echo "$QUALITY_GATE_STATUS" | jq -r '.projectStatus.conditions | all(.status == "OK")')
+  #           if [[ "$PROJECT_STATUS" != "OK" || "$ALL_CONDITIONS_OK" != "true" ]]; then
+  #             echo "Quality Gate failed. Stopping the workflow."
+  #             exit 1
+  #           else
+  #             echo "Quality Gate passed."
+  #           fi
+  #       shell: bash
 
-  push_to_nexus_tag:
-    runs-on: ubuntu-latest
-    needs: sonar_scan
-    if: startsWith(github.ref, 'refs/tags/')
-    environment: nexus-approval
-    steps:
-      - name: Download Package Artifact
-        uses: actions/download-artifact@v3
-        with:
-          name: nuget-package
-          path: ./bin/Release
+  # push_to_nexus_tag:
+  #   runs-on: ubuntu-latest
+  #   needs: sonar_scan
+  #   if: startsWith(github.ref, 'refs/tags/')
+  #   environment: nexus-approval
+  #   steps:
+  #     - name: Download Package Artifact
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: nuget-package
+  #         path: ./bin/Release
 
-      - name: List files in Release directory
-        run: ls -al ./bin/Release
+  #     - name: List files in Release directory
+  #       run: ls -al ./bin/Release
 
-      - name: Push to Nexus Repository (Tag)
-        env:
-          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
-          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
-          NEXUS_API_KEY: ${{ secrets.NEXUS_API_KEY }}
-        run: |
-          echo "Pushing to Nexus repository for tag: http://52.187.94.85:8081/repository/nuget-tag"
-          dotnet nuget push ./bin/Release/*.nupkg --source http://52.187.94.85:8081/repository/nuget-tag --api-key $NEXUS_API_KEY
+  #     - name: Push to Nexus Repository (Tag)
+  #       env:
+  #         NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
+  #         NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
+  #         NEXUS_API_KEY: ${{ secrets.NEXUS_API_KEY }}
+  #       run: |
+  #         echo "Pushing to Nexus repository for tag: http://52.187.94.85:8081/repository/nuget-tag"
+  #         dotnet nuget push ./bin/Release/*.nupkg --source http://52.187.94.85:8081/repository/nuget-tag --api-key $NEXUS_API_KEY
 
-  push_to_nexus_branch:
-    runs-on: ubuntu-latest
-    needs: sonar_scan
-    if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/release'
-    steps:
-      - name: Download Package Artifact
-        uses: actions/download-artifact@v3
-        with:
-          name: nuget-package
-          path: ./bin/Release
+  # push_to_nexus_branch:
+  #   runs-on: ubuntu-latest
+  #   needs: sonar_scan
+  #   if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/release'
+  #   steps:
+  #     - name: Download Package Artifact
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: nuget-package
+  #         path: ./bin/Release
 
-      - name: List files in Release directory
-        run: ls -al ./bin/Release
+  #     - name: List files in Release directory
+  #       run: ls -al ./bin/Release
 
-      - name: Push to Nexus Repository (Branch)
-        env:
-          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
-          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
-          NEXUS_API_KEY: ${{ secrets.NEXUS_API_KEY }}
-        run: |
-          if [[ "${GITHUB_REF}" == "refs/heads/development" ]]; then
-            NEXUS_SOURCE="http://52.187.94.85:8081/repository/nuget-snapshot"
-          elif [[ "${GITHUB_REF}" == "refs/heads/release" ]]; then
-            NEXUS_SOURCE="http://52.187.94.85:8081/repository/nuget-rc"
-          fi
-          echo "Pushing to Nexus repository: $NEXUS_SOURCE"
-          dotnet nuget push ./bin/Release/*.nupkg --source $NEXUS_SOURCE --api-key $NEXUS_API_KEY
+  #     - name: Push to Nexus Repository (Branch)
+  #       env:
+  #         NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
+  #         NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
+  #         NEXUS_API_KEY: ${{ secrets.NEXUS_API_KEY }}
+  #       run: |
+  #         if [[ "${GITHUB_REF}" == "refs/heads/development" ]]; then
+  #           NEXUS_SOURCE="http://52.187.94.85:8081/repository/nuget-snapshot"
+  #         elif [[ "${GITHUB_REF}" == "refs/heads/release" ]]; then
+  #           NEXUS_SOURCE="http://52.187.94.85:8081/repository/nuget-rc"
+  #         fi
+  #         echo "Pushing to Nexus repository: $NEXUS_SOURCE"
+  #         dotnet nuget push ./bin/Release/*.nupkg --source $NEXUS_SOURCE --api-key $NEXUS_API_KEY
